# Generated by Django 3.1.6 on 2021-02-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatar.png', upload_to='users/'),
        ),
    ]
