# Generated by Django 3.1.6 on 2021-02-17 19:29

import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='sellers/default.png', upload_to=services.models.seller_image_path)),
                ('phone', models.CharField(max_length=20)),
                ('wait_time', models.IntegerField(default=30)),
                ('service_time', models.IntegerField(blank=True, null=True)),
                ('open_time', models.TimeField(default=datetime.time(9, 0))),
                ('close_time', models.TimeField(default=datetime.time(22, 0))),
                ('delivery', models.CharField(choices=[('F', 'Free delivery'), ('P', 'Delivery Fee')], default='F', max_length=1)),
                ('has_tables', models.BooleanField(default=False)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('cols', models.IntegerField(blank=True, null=True)),
                ('has_timeslots', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='categories/default.png', upload_to=services.models.category_image_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='services.service')),
            ],
        ),
    ]
