# Generated by Django 3.1.6 on 2021-02-18 16:37

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to=services.models.product_image_path),
        ),
    ]
