# Generated by Django 3.1.6 on 2021-02-19 08:38

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='thumbnail',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to=services.models.product_image_path),
        ),
    ]
