# Generated by Django 3.1.6 on 2021-02-19 08:39

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_seller_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='thumbnail',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to=services.models.seller_image_path),
        ),
    ]
