# Generated by Django 3.1.6 on 2021-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210219_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='delivery',
            field=models.CharField(choices=[('F', 'Free Delivery'), ('P', 'Paid Delivery')], default='F', max_length=1),
        ),
    ]
