# Generated by Django 3.1.6 on 2021-02-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210219_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='thumbnail',
        ),
    ]
