# Generated by Django 3.1.6 on 2021-02-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210220_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='has_tables',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='has_timeslots',
        ),
    ]
