# Generated by Django 3.1.6 on 2021-02-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210221_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='rows',
        ),
    ]
