# Generated by Django 3.1.6 on 2021-03-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_seller_service_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
