# Generated by Django 3.1.6 on 2021-03-02 09:14

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20210302_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=services.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=services.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(upload_to=services.models.seller_image_path),
        ),
    ]
