# Generated by Django 3.1.6 on 2021-03-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_auto_20210226_0155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
    ]
