# Generated by Django 3.1.6 on 2021-03-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0005_auto_20210301_0624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
    ]
