# Generated by Django 3.1.6 on 2021-03-01 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_remove_seller_service_time'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviw',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('paid', 'Paid')], default='booked', max_length=10),
        ),
    ]
